apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: DEBUG
              value: "False"
            - name: DJANGO_DB_HOST
              value: $(DB_SERVICE_HOST)
            - name: DJANGO_DB_NAME
              value: app
            - name: DJANGO_DB_PASS
              value: worker
            - name: DJANGO_DB_PORT
              value: "5432"
            - name: DJANGO_DB_USER
              value: worker
            - name: DJANGO_DEBUG
              value: "False"
          image: ghcr.io/wbotu56/proj0-app:latest
          livenessProbe:
            exec:
              command:
                - wget --no-verbose --tries=1 -qO- http://$(APP_SERVICE_HOST):$(APP_SERVICE_PORT)/health/ | grep -c up || exit 1
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: app
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
