name: proj0

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: /run/secrets/db_password
      POSTGRES_USER: worker
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U worker -d app"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1s
  app:
    image: ghcr.io/wbotu56/proj0-app:${TAG:-latest}
    build:
      context: .
      dockerfile: app.Dockerfile
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: app
      DJANGO_DB_PASS: /run/secrets/db_password
      DJANGO_DB_PORT: "5432"
      DJANGO_DB_USER: worker
      DJANGO_DEBUG: "False"
      DEBUG: "False"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "0.0.0.0:8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 -qO- http://app:8000/health/ | grep -c up || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - mediauploads:/app/media/uploads:rw

volumes:
  pgdata:
  mediauploads:

secrets:
  db_password:
    environment: POSTGRES_PASSWORD
